global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'temperature'
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'websyssac-6v3wyclgaa-uc.a.run.app'
